### ISSUE TITLE
"Assigned To" not optional

### ISSUE THREAD

**Issue by papa-pep** [MicrosoftPremier/VstsExtensions#12]
It appears that the "Assigned To" field is not optional as the documentation suggests.

Error in log: "Input required: assignedTo"

**Comment by ReneSchumacher** [comment]
Hey Greg,

sorry for that. I didn't realize I always tested with an identity and the code actually treated Assigned To as required. Give me about five minutes and I release an update.

Cheers,
René

**Comment by ReneSchumacher** [comment]
The update is public. This should fix the issue. If not, please let me know an I'll reopen the issue.

**Comment by papa-pep** [comment]
Thank you!

**Comment by papa-pep** [comment]
I'm not sure it's related, but I can no longer view the build that contained the step.  All others work fine. 

![image](https://user-images.githubusercontent.com/13069258/44805265-56cdd780-ab89-11e8-9261-29577c16795b.png)

**Comment by ReneSchumacher** [comment]
Hey, sorry for the late reply. I'm glad you confirmed that the issue is fixed now. The new issue shouldn't be related to the task update - at least I cannot think of any way a new task version should impact the rendering of the build summary UI.

If I understand your addition correctly, the second issue is gone by now? Otherwise I might be able to help investigate the root cause.

**Comment by papa-pep** [comment]
I'm still experiencing the error mentioned above.  I've also opened a ticket with vsts but haven't received a reply yet.

**Comment by papa-pep** [comment]
Case number: 118083018897642
